### ISSUE TITLE
support no 'files' param in tsconfig.json

### ISSUE THREAD

**Issue by altano** [blakeembrey/typescript-simple-loader#1]
It looks like this loader requires the 'files' param in tsconfig, although it is defined to be optional.  Omitting it is supposed to compile all ts files in the directory.

**Comment by blakeembrey** [comment]
@altano I shouldn't require `files` since it's inferred based on the first TypeScript file, but I'd have to confirm. I'm not sure whether it makes sense to compile all files in the directory for Webpack. I'll have to play around and see whether it's even possible with Webpack too.

**Comment by altano** [comment]
It doesn't work as is.  There's a .map call on files, which if undefined, throws an exception.

It sort of actually doesn't make sense to support an empty files array with webpack right now since the node_modules directory will throw everything into error, and you can't yet exclude it with TypeScript 1.5.  They added support to exclude node_modules but it won't ship till 1.6.

I'm currently experimenting with atom-typescript plugin for Atom, which has the ability to take a 'filesGlob' option in the tsconfig and it maintains the files array for you based on the glob.  The only reasonable solution I've found so far...

How are you using tsconfig in projects?  Are you maintaining the files array by hand?

**Comment by blakeembrey** [comment]
@altano Ok, I'll make sure the error is fixed up. It's not actually required, but I should leave a comment on what happens if it's omitted in the README.

For my own projects, yes definitely using `tsconfig.json` and yes I'm maintaining the files array by hand. But honestly, it's not actually that many files. You don't need an array of _every_ file you want to compile, just the entry points. If you're using TSD (or have a global definition file) and it's a Node/Webpack/etc. project, it's likely you only have two files needed in that array.

Edit: I'll get around to it in the next couple of days :smile: 

Edit 2: Actually, it does get trickier with test files, you're correct. If forgotten to compile them a couple of times. What I'd actually like to do for that is make the test runner accept TypeScript files though, but I only have so much time to work on each project.

**Comment by altano** [comment]
Oh, I see, that's completely reasonable.  Thanks!

**Comment by altano** [comment]
(feel free to reopen this if you want to use it to track the issue, but I'm closing since it isn't really an issue since as you point out you can't really use it without a files array with webpack)

**Comment by blakeembrey** [comment]
@altano See edit 2, just in case you missed it.

Also, if there's interest, I do intend to spend some time writing a node transpiler that can be used transparently (just `--require ...` in mocha or something like `tsnode script.ts`). Right now, the closest thing is `typescript-require`, but it's a buggy mess at best.
